services:
  triton:
    image: nvcr.io/nvidia/tritonserver:25.09-py3
    container_name: triton
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ipc: host
    ulimits:
      memlock: -1
      stack: 67108864
    command: >
      tritonserver
      --model-repository=/models
      --log-verbose=1
      --model-control-mode=explicit
      --load-model=mnist
      --load-model=mnist_onnx
    volumes:
      - ./models:/models
      - ./target/release/libtriton_custom_backend.so:/opt/tritonserver/backends/custom_backend/libtriton_custom_backend.so
    ports:
      - "8000:8000" # HTTP
      - "8001:8001" # gRPC
      - "8002:8002" # metrics (Prometheus)
