[package]
name = "triton-ng"
version = "0.1.0"
edition = "2024"

[features]
cuda = []

[dependencies]
byteorder = { workspace = true }
crossbeam = { workspace = true }
libc = { workspace = true }
serde_json = { workspace = true }
triton-ng-macros = { workspace = true }
triton-ng-sys = { workspace = true }

[lints]
workspace = true
